# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59b6a217fe4887ff6ff0ed0ad0a67d6e0474c690f15aa6ddf93753265379cac4f6e3cfc0e391ff77b8b1aa1987cd2220cbdc1883ee7e2416eb6748eeaf744c4e

test:
  secret_key_base: 7d83290a4fd86a0592efadc427c06950691221504e811cf99c106c22349ac2e010df1dc9decb15ae5cfe2143070c9f311233bc4276fafcb3b0e65ba7855c76ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
